name: scrap
channels:
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - pydantic
  - pandas-stubs==2.3.2.250926
  - pyarrow
  - fastparquet
  - httpx
  - python-dotenv
  - dnspython
